with-venv supports --embedded

diff --git a/bin/with-venv b/bin/with-venv
--- a/bin/with-venv
+++ b/bin/with-venv
@@ -2,9 +2,22 @@
 set -eu -o pipefail
 
 # > with-venv --python python3.10 -r requirements.txt -- python test.py -y --path=/here
+# > with-venv --embedded test.py -- python test.py -y --path=/here
 
-zparseopts -D -E -F -A opts - -python: r:
+zparseopts -D -E -F -A opts - -python: r: -embedded:
 if [[ $1 == '--' ]]; then shift; fi
+
+if [[ -v opts[--embedded] ]]; then
+    if sed -n -E '/^"""! [^ ]+ requirements$/ , /^""".*$/ {q1}' $opts[--embedded]; then
+        echo "Cannot find embedded requirements in" $opts[--embedded] "." >&2
+        exit 1
+    fi
+    # TODO doesnt complain if you have more than one requirements section
+    python=$(sed -n -E 's/^"""! ([^ ]+) requirements$/\1/p' $opts[--embedded])
+    requirements=$(sed -n -E '/^"""! [^ ]+ requirements$/ , /^""".*$/ { /^"""/d; p }' $opts[--embedded])
+    $0 --python $python -r <(print -- $requirements) -- $@
+    exit
+fi
 
 python=${opts[--python]:-python3.10}
 requirements=$(sort $opts[-r])
