nn/run on aws needs no aws credentials

diff --git a/bin/nn/run b/bin/nn/run
--- a/bin/nn/run
+++ b/bin/nn/run
@@ -60,11 +60,15 @@ args+=(
 )
 
 # aws
+if [[ -e ~/.aws/credentials ]]; then
+    args+=(
+        --env AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
+        --env AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
+    ) || (echo 'cannot get aws credentials'; exit 1)
+fi
 args+=(
-    --env AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
-    --env AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
     --env AWS_DEFAULT_REGION=eu-west-1
-) || (echo 'cannot get aws credentials'; exit 1)
+)
 
 # s3 cache
 if [[ -e $h/s3-cache ]]; then
