chrome/setup always tries to set preferences

diff --git a/i/chrome/setup b/i/chrome/setup
--- a/i/chrome/setup
+++ b/i/chrome/setup
@@ -10,42 +10,41 @@ set -eux -o pipefail
 if ! which google-chrome; then
     # install from deb file
     # it will also add apt sources for later updates
-    wget --fail \
+    wget \
         'https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb' \
         -O /tmp/google-chrome.deb
-    sudo apt-get install -yqq /tmp/google-chrome.deb
+    sudo apt-get install -qy /tmp/google-chrome.deb
     rm /tmp/google-chrome.deb
 
     # NOTE: at this point apt has it in the index
     # there is google-chrome-stable, google-chrome-beta, google-chrome-unstable
-
-    apts=(
-        jq # parse json to change preferences
-        moreutils # for sponge
-        fonts-stix # some math pages seem to need that (also useful for firefox or other browsers)
-    )
-    sudo apt-get -yqq install $apts
-
-    (
-        f=~/.config/google-chrome/Default/Preferences
-        if [[ ! -f $f ]]; then
-            if [[ -v DISPLAY ]]; then
-                echo 'start and exit chrome to intialize and adapt config files'
-                google-chrome
-            else
-                echo 'cant start chrome because no DISPLAY'
-                exit 1
-            fi
-        fi
-        while [[ ! -f $f ]]; do
-            sleep 1s
-            echo "waiting for chrome to initialize $f"
-        done
-        # system border works better with tiling window managers
-        jq '.browser.custom_chrome_frame=false' $f | sponge $f
-    )
-
 fi
+
+apts=(
+    jq # parse json to change preferences
+    moreutils # for sponge
+    fonts-stix # some math pages seem to need that (also useful for firefox or other browsers)
+)
+sudo apt-get -qy install $apts
+
+(
+    f=~/.config/google-chrome/Default/Preferences
+    if [[ ! -f $f ]]; then
+        if [[ -v DISPLAY ]]; then
+            echo 'Start and exit chrome to intialize and adapt config files.'
+            google-chrome
+        else
+            echo 'Cannot start chrome because no DISPLAY.' 2>&1
+            exit 1
+        fi
+    fi
+    while [[ ! -f $f ]]; do
+        sleep 1s
+        echo "waiting for chrome to initialize $f"
+    done
+    # system border works better with tiling window managers
+    jq '.browser.custom_chrome_frame=false' $f | sponge $f
+)
 
 # make xdg use whatever is in bin/chrome
 cat >~/.local/share/applications/dkuettel-chrome.desktop <<- 'EOF'
@@ -53,6 +52,7 @@ cat >~/.local/share/applications/dkuettel-chrome.desktop <<- 'EOF'
 Terminal=false
 Exec=chrome
 EOF
+# NOTE these xdg-settings calls are incredibly slow
 xdg-settings set default-web-browser dkuettel-chrome.desktop
 xdg-settings set default-url-scheme-handler http dkuettel-chrome.desktop
 xdg-settings set default-url-scheme-handler https dkuettel-chrome.desktop
