try to make the main setups resumable

diff --git a/i/desktop/attended-setup b/i/desktop/attended-setup
--- a/i/desktop/attended-setup
+++ b/i/desktop/attended-setup
@@ -1,6 +1,9 @@
 #!/bin/zsh
 set -eux -o pipefail
 
+this=$0
+continue_from=${1:-}
+
 cd ${0:a:h}
 
 setups=(
@@ -9,9 +12,24 @@ setups=(
     dropbox
 )
 
+if [[ $continue_from != '' ]]; then
+    at=$setups[(i)$continue_from]
+    if [[ $at -gt $#setups ]]; then
+        echo "Cannot find $continue_from to continue from." 1>&2
+        exit 1
+    fi
+    setups=$setups[$at,-1]
+fi
+
+function TRAPZERR {
+    echo 'Setup failed for "'$i'". Fix and then resume with "'$this $i'".'
+}
+set +x
 for i in $setups; do
     ../$i/setup
 done
+set -x
+unset -f TRAPZERR
 
 cat <<- EON
 Some notes:
diff --git a/i/desktop/setup b/i/desktop/setup
--- a/i/desktop/setup
+++ b/i/desktop/setup
@@ -1,6 +1,9 @@
 #!/bin/zsh
 set -eux -o pipefail
 
+this=$0
+continue_from=${1:-}
+
 cd ${0:a:h}
 
 source ../zsh/path.zsh
@@ -78,8 +81,24 @@ setups=(
     ltstatus
     pstart
 )
+
+if [[ $continue_from != '' ]]; then
+    at=$setups[(i)$continue_from]
+    if [[ $at -gt $#setups ]]; then
+        echo "Cannot find $continue_from to continue from." 1>&2
+        exit 1
+    fi
+    setups=$setups[$at,-1]
+fi
+
+function TRAPZERR {
+    echo 'Setup failed for "'$i'". Fix and then resume with "'$this $i'".'
+}
+set +x
 for i in $setups; do
     ../$i/setup
 done
+set -x
+unset -f TRAPZERR
 
 echo 'Use i/desktop/attended-setup when in X.'
diff --git a/i/server/setup b/i/server/setup
--- a/i/server/setup
+++ b/i/server/setup
@@ -1,6 +1,9 @@
 #!/bin/zsh
 set -eux -o pipefail
 
+this=$0
+continue_from=${1:-}
+
 cd ${0:a:h}
 
 # see that we also checked out all submodules
@@ -89,9 +92,26 @@ setups=(
     kvm
     exa
 )
+
+if [[ $continue_from != '' ]]; then
+    at=$setups[(i)$continue_from]
+    if [[ $at -gt $#setups ]]; then
+        echo "Cannot find $continue_from to continue from." 1>&2
+        exit 1
+    fi
+    setups=$setups[$at,-1]
+fi
+
+function TRAPZERR {
+    echo 'Setup failed for "'$i'". Fix and then resume with "'$this $i'".'
+}
+set +x
 for i in $setups; do
+    echo '---------------[[' $i ']]---------------'
     ../$i/setup
 done
+set -x
+unset -f TRAPZERR
 
 # switch to hwe kernels (rolling updates)
 # NOTE at the end, so that above apts hopefully dont complain about "kernel update in progress" (requires restart)
