make nvim setup fail if PlugInstall failed

diff --git a/i/vim/setup-nvim b/i/vim/setup-nvim
--- a/i/vim/setup-nvim
+++ b/i/vim/setup-nvim
@@ -28,5 +28,17 @@ if [[ ! -f ~/.local/share/nvim/site/autoload/plug.vim ]]; then
     curl --fail --location --create-dirs \
         --output ~/.local/share/nvim/site/autoload/plug.vim \
         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
-    nvim -c PlugInstall -c qa
+
+    log=$(tempfile)
+    nvim -c PlugInstall -c "w $log" -c qa
+
+    # hacky check if any plugin failed to install
+    # (the output of plug starts with an "x" on a failed item)
+    if egrep '^x' $log; then
+        cat $log
+        exit 1
+    fi
+
+    rm $log
+
 fi
